import {
  BookData,
  Canon,
  CanonBook,
  CanonData,
  Category,
  DeuterocanonBook,
  DeuterocanonData,
  Language,
  Testament,
} from './bible.js';
import { CaseInsensitiveMap } from './util/case-insensitive-map.js';

/**
 * Data for all books of the canon.
 */
export const CanonBooks: CanonData = {
  [CanonBook.Genesis]: {
    name: {
      [Language.English]: 'Genesis',
      [Language.Spanish]: 'Génesis',
      [Language.Chinese]: '創 世 記',
      [Language.Korean]: '창세기',
      [Language.Japanese]: '創世記',
      [Language.Portuguese]: 'Gênesis',
      [Language.French]: 'Genèse',
      [Language.German]: '1 Mose',
      [Language.Italian]: 'Genesi',
      [Language.Hindi]: 'उत्पत्ति',
    },
    abbreviation: CanonBook.Genesis,
    testament: Testament.Old,
    categories: Category.Instruction | Category.Pentateuch,
    chapters: 50,
    canon: Canon.Canon,
  },
  [CanonBook.Exodus]: {
    name: {
      [Language.English]: 'Exodus',
      [Language.Spanish]: 'Éxodo',
      [Language.Chinese]: '出 埃 及 記',
      [Language.Korean]: '출애굽기',
      [Language.Japanese]: '出エジプト記',
      [Language.Portuguese]: 'Êxodo',
      [Language.French]: 'Exode',
      [Language.German]: '2 Mose',
      [Language.Italian]: 'Esodo',
      [Language.Hindi]: 'निर्गमन',
    },
    abbreviation: CanonBook.Exodus,
    testament: Testament.Old,
    categories: Category.Instruction | Category.Pentateuch,
    chapters: 40,
    canon: Canon.Canon,
  },
  [CanonBook.Leviticus]: {
    name: {
      [Language.English]: 'Leviticus',
      [Language.Spanish]: 'Levítico',
      [Language.Chinese]: '利 未 記',
      [Language.Korean]: '레위기',
      [Language.Japanese]: 'レビ記',
      [Language.Portuguese]: 'Levítico',
      [Language.French]: 'Lévitique',
      [Language.German]: '3 Mose',
      [Language.Italian]: 'Levitico',
      [Language.Hindi]: 'लैव्यव्यवस्था',
    },
    abbreviation: CanonBook.Leviticus,
    testament: Testament.Old,
    categories: Category.Instruction | Category.Pentateuch,
    chapters: 27,
    canon: Canon.Canon,
  },
  [CanonBook.Numbers]: {
    name: {
      [Language.English]: 'Numbers',
      [Language.Spanish]: 'Números',
      [Language.Chinese]: '民 數 記',
      [Language.Korean]: '민수기',
      [Language.Japanese]: '民数記',
      [Language.Portuguese]: 'Números',
      [Language.French]: 'Nombres',
      [Language.German]: '4 Mose',
      [Language.Italian]: 'Numeri',
      [Language.Hindi]: 'गिनती',
    },
    abbreviation: CanonBook.Numbers,
    testament: Testament.Old,
    categories: Category.Instruction | Category.Pentateuch,
    chapters: 36,
    canon: Canon.Canon,
  },
  [CanonBook.Deuteronomy]: {
    name: {
      [Language.English]: 'Deuteronomy',
      [Language.Spanish]: 'Deuteronomio',
      [Language.Chinese]: '申 命 記',
      [Language.Korean]: '신명기',
      [Language.Japanese]: '申命記',
      [Language.Portuguese]: 'Deuteronômio',
      [Language.French]: 'Deutéronome',
      [Language.German]: '5 Mose',
      [Language.Italian]: 'Deuteronomio',
      [Language.Hindi]: 'व्यवस्था विवरण',
    },
    abbreviation: CanonBook.Deuteronomy,
    testament: Testament.Old,
    categories: Category.Instruction | Category.Pentateuch,
    chapters: 34,
    canon: Canon.Canon,
  },
  [CanonBook.Joshua]: {
    name: {
      [Language.English]: 'Joshua',
      [Language.Spanish]: 'Josué',
      [Language.Chinese]: '約 書 亞 記',
      [Language.Korean]: '여호수아',
      [Language.Japanese]: 'ヨシュア記',
      [Language.Portuguese]: 'Josué',
      [Language.French]: 'Josué',
      [Language.German]: 'Josua',
      [Language.Italian]: 'Giosué',
      [Language.Hindi]: 'यहोशू',
    },
    abbreviation: CanonBook.Joshua,
    testament: Testament.Old,
    categories: Category.Prophets | Category.FormerProphets | Category.HistoricalNarrative,
    chapters: 24,
    canon: Canon.Canon,
  },
  [CanonBook.Judges]: {
    name: {
      [Language.English]: 'Judges',
      [Language.Spanish]: 'Jueces',
      [Language.Chinese]: '士 師 記',
      [Language.Korean]: '사사기',
      [Language.Japanese]: '士師記',
      [Language.Portuguese]: 'Juízes',
      [Language.French]: 'Juges',
      [Language.German]: 'Richter',
      [Language.Italian]: 'Giudici',
      [Language.Hindi]: 'न्यायियों',
    },
    abbreviation: CanonBook.Judges,
    testament: Testament.Old,
    categories: Category.Prophets | Category.FormerProphets | Category.HistoricalNarrative,
    chapters: 21,
    canon: Canon.Canon,
  },
  [CanonBook.Ruth]: {
    name: {
      [Language.English]: 'Ruth',
      [Language.Spanish]: 'Rut',
      [Language.Chinese]: '路 得 記',
      [Language.Korean]: '룻기',
      [Language.Japanese]: 'ルツ記',
      [Language.Portuguese]: 'Rute',
      [Language.French]: 'Ruth',
      [Language.German]: 'Rut',
      [Language.Italian]: 'Rut',
      [Language.Hindi]: 'रूत',
    },
    abbreviation: CanonBook.Ruth,
    testament: Testament.Old,
    categories: Category.Writings | Category.Scrolls | Category.HistoricalNarrative,
    chapters: 4,
    canon: Canon.Canon,
  },
  [CanonBook.FirstSamuel]: {
    name: {
      [Language.English]: '1 Samuel',
      [Language.Spanish]: '1 Samuel',
      [Language.Chinese]: '撒 母 耳 記 上',
      [Language.Korean]: '사무엘상',
      [Language.Japanese]: 'サムエル記Ⅰ',
      [Language.Portuguese]: '1 Samuel',
      [Language.French]: '1 Samuel',
      [Language.German]: '1 Samuel',
      [Language.Italian]: '1 Samuele',
      [Language.Hindi]: '1 शमूएल',
    },
    abbreviation: CanonBook.FirstSamuel,
    testament: Testament.Old,
    categories: Category.Prophets | Category.FormerProphets | Category.HistoricalNarrative,
    chapters: 31,
    canon: Canon.Canon,
  },
  [CanonBook.SecondSamuel]: {
    name: {
      [Language.English]: '2 Samuel',
      [Language.Spanish]: '2 Samuel',
      [Language.Chinese]: '撒 母 耳 記 下',
      [Language.Korean]: '사무엘하',
      [Language.Japanese]: 'サムエル記Ⅱ',
      [Language.Portuguese]: '2 Samuel',
      [Language.French]: '2 Samuel',
      [Language.German]: '2 Samuel',
      [Language.Italian]: '2 Samuele',
      [Language.Hindi]: '2 शमूएल',
    },
    abbreviation: CanonBook.SecondSamuel,
    testament: Testament.Old,
    categories: Category.Prophets | Category.FormerProphets | Category.HistoricalNarrative,
    chapters: 24,
    canon: Canon.Canon,
  },
  [CanonBook.FirstKings]: {
    name: {
      [Language.English]: '1 Kings',
      [Language.Spanish]: '1 Reyes',
      [Language.Chinese]: '列 王 紀 上',
      [Language.Korean]: '열왕기상',
      [Language.Japanese]: '列王記Ⅰ',
      [Language.Portuguese]: '1 Reis',
      [Language.French]: '1 Rois',
      [Language.German]: '1 Koenige',
      [Language.Italian]: '1 Re',
      [Language.Hindi]: '1 राजा',
    },
    abbreviation: CanonBook.FirstKings,
    testament: Testament.Old,
    categories: Category.Prophets | Category.FormerProphets | Category.HistoricalNarrative,
    chapters: 22,
    canon: Canon.Canon,
  },
  [CanonBook.SecondKings]: {
    name: {
      [Language.English]: '2 Kings',
      [Language.Spanish]: '2 Reyes',
      [Language.Chinese]: '列 王 紀 下',
      [Language.Korean]: '열왕기하',
      [Language.Japanese]: '列王記Ⅱ',
      [Language.Portuguese]: '2 Reis',
      [Language.French]: '2 Rois',
      [Language.German]: '2 Koenige',
      [Language.Italian]: '2 Re',
      [Language.Hindi]: '2 राजा',
    },
    abbreviation: CanonBook.SecondKings,
    testament: Testament.Old,
    categories: Category.Prophets | Category.FormerProphets | Category.HistoricalNarrative,
    chapters: 25,
    canon: Canon.Canon,
  },
  [CanonBook.FirstChronicles]: {
    name: {
      [Language.English]: '1 Chronicles',
      [Language.Spanish]: '1 Crónicas',
      [Language.Chinese]: '歷 代 志 上',
      [Language.Korean]: '역대상',
      [Language.Japanese]: '歴代誌Ⅰ',
      [Language.Portuguese]: '1 Crônicas',
      [Language.French]: '1 Chroniques',
      [Language.German]: '1 Chronik',
      [Language.Italian]: '1 Cronache',
      [Language.Hindi]: '1 इतिहास',
    },
    abbreviation: CanonBook.FirstChronicles,
    testament: Testament.Old,
    categories: Category.Writings | Category.Historical | Category.HistoricalNarrative,
    chapters: 29,
    canon: Canon.Canon,
  },
  [CanonBook.SecondChronicles]: {
    name: {
      [Language.English]: '2 Chronicles',
      [Language.Spanish]: '2 Crónicas',
      [Language.Chinese]: '歷 代 志 下',
      [Language.Korean]: '역대하',
      [Language.Japanese]: '歴代誌Ⅱ',
      [Language.Portuguese]: '2 Crônicas',
      [Language.French]: '2 Chroniques',
      [Language.German]: '2 Chronik',
      [Language.Italian]: '2 Cronache',
      [Language.Hindi]: '2 इतिहास',
    },
    abbreviation: CanonBook.SecondChronicles,
    testament: Testament.Old,
    categories: Category.Writings | Category.Historical | Category.HistoricalNarrative,
    chapters: 36,
    canon: Canon.Canon,
  },
  [CanonBook.Ezra]: {
    name: {
      [Language.English]: 'Ezra',
      [Language.Spanish]: 'Esdras',
      [Language.Chinese]: '以 斯 拉 記',
      [Language.Korean]: '에스라',
      [Language.Japanese]: 'エズラ記',
      [Language.Portuguese]: 'Esdras',
      [Language.French]: 'Esdras',
      [Language.German]: 'Esra',
      [Language.Italian]: 'Esdra',
      [Language.Hindi]: 'एज्रा',
    },
    abbreviation: CanonBook.Ezra,
    testament: Testament.Old,
    categories: Category.Writings | Category.Historical | Category.HistoricalNarrative,
    chapters: 10,
    canon: Canon.Canon,
  },
  [CanonBook.Nehemiah]: {
    name: {
      [Language.English]: 'Nehemiah',
      [Language.Spanish]: 'Nehemías',
      [Language.Chinese]: '尼 希 米 記',
      [Language.Korean]: '느헤미야',
      [Language.Japanese]: 'ネヘミヤ 記',
      [Language.Portuguese]: 'Neemias',
      [Language.French]: 'Néhémie',
      [Language.German]: 'Nehemia',
      [Language.Italian]: 'Neemia',
      [Language.Hindi]: 'नहेमायाह',
    },
    abbreviation: CanonBook.Nehemiah,
    testament: Testament.Old,
    categories: Category.Writings | Category.Historical | Category.HistoricalNarrative,
    chapters: 13,
    canon: Canon.Canon,
  },
  [CanonBook.Esther]: {
    name: {
      [Language.English]: 'Esther',
      [Language.Spanish]: 'Ester',
      [Language.Chinese]: '以 斯 帖 記',
      [Language.Korean]: '에스더',
      [Language.Japanese]: 'エステル 記',
      [Language.Portuguese]: 'Ester',
      [Language.French]: 'Esther',
      [Language.German]: 'Ester',
      [Language.Italian]: 'Ester',
      [Language.Hindi]: 'एस्तेर',
    },
    abbreviation: CanonBook.Esther,
    testament: Testament.Old,
    categories: Category.Writings | Category.Scrolls | Category.HistoricalNarrative,
    chapters: 10,
    canon: Canon.Canon,
  },
  [CanonBook.Job]: {
    name: {
      [Language.English]: 'Job',
      [Language.Spanish]: 'Job',
      [Language.Chinese]: '約 伯 記',
      [Language.Korean]: '욥기',
      [Language.Japanese]: 'ヨブ 記',
      [Language.Portuguese]: 'Jó',
      [Language.French]: 'Job',
      [Language.German]: 'Hiob',
      [Language.Italian]: 'Giobbe',
      [Language.Hindi]: 'अय्यूब',
    },
    abbreviation: CanonBook.Job,
    testament: Testament.Old,
    categories: Category.Writings | Category.Poetic | Category.Wisdom | Category.Sapiental,
    chapters: 42,
    canon: Canon.Canon,
  },
  [CanonBook.Psalm]: {
    name: {
      [Language.English]: 'Psalm',
      [Language.Spanish]: 'Salmos',
      [Language.Chinese]: '詩 篇',
      [Language.Korean]: '시편',
      [Language.Japanese]: '詩篇',
      [Language.Portuguese]: 'Salmos',
      [Language.French]: 'Psaumes',
      [Language.German]: 'Psalm',
      [Language.Italian]: 'Salmi',
      [Language.Hindi]: 'भजन संहिता',
    },
    abbreviation: CanonBook.Psalm,
    testament: Testament.Old,
    categories: Category.Writings | Category.Poetic | Category.Wisdom | Category.Sapiental,
    chapters: 150,
    canon: Canon.Canon,
  },
  [CanonBook.Proverbs]: {
    name: {
      [Language.English]: 'Proverbs',
      [Language.Spanish]: 'Proverbios',
      [Language.Chinese]: '箴 言',
      [Language.Korean]: '잠언',
      [Language.Japanese]: '箴言 知恵の泉',
      [Language.Portuguese]: 'Provérbios',
      [Language.French]: 'Proverbes',
      [Language.German]: 'Sprueche',
      [Language.Italian]: 'Proverbi',
      [Language.Hindi]: 'नीतिवचन',
    },
    abbreviation: CanonBook.Proverbs,
    testament: Testament.Old,
    categories: Category.Writings | Category.Poetic | Category.Wisdom | Category.Sapiental,
    chapters: 31,
    canon: Canon.Canon,
  },
  [CanonBook.Ecclesiastes]: {
    name: {
      [Language.English]: 'Ecclesiastes',
      [Language.Spanish]: 'Eclesiastés',
      [Language.Chinese]: '傳 道 書',
      [Language.Korean]: '전도서',
      [Language.Japanese]: '伝道者の書',
      [Language.Portuguese]: 'Eclesiastes',
      [Language.French]: 'Ecclésiaste',
      [Language.German]: 'Prediger',
      [Language.Italian]: 'Ecclesiaste',
      [Language.Hindi]: 'सभोपदेशक',
    },
    abbreviation: CanonBook.Ecclesiastes,
    testament: Testament.Old,
    categories: Category.Writings | Category.Scrolls | Category.Wisdom | Category.Sapiental,
    chapters: 12,
    canon: Canon.Canon,
  },
  [CanonBook.SongOfSongs]: {
    name: {
      [Language.English]: 'Song of Songs',
      [Language.Spanish]: 'Cantares',
      [Language.Chinese]: '雅 歌',
      [Language.Korean]: '아가',
      [Language.Japanese]: '雅歌',
      [Language.Portuguese]: 'Cantares',
      [Language.French]: 'Cantique des Cantiques',
      [Language.German]: 'Hohelied',
      [Language.Italian]: 'Cantico dei Cantici',
      [Language.Hindi]: 'श्रेष्ठगीत',
    },
    abbreviation: CanonBook.SongOfSongs,
    testament: Testament.Old,
    categories: Category.Writings | Category.Scrolls | Category.Wisdom | Category.Sapiental,
    chapters: 8,
    canon: Canon.Canon,
  },
  [CanonBook.Isaiah]: {
    name: {
      [Language.English]: 'Isaiah',
      [Language.Spanish]: 'Isaías',
      [Language.Chinese]: '以 賽 亞 書',
      [Language.Korean]: '이사야',
      [Language.Japanese]: 'イザヤ書',
      [Language.Portuguese]: 'Isaías',
      [Language.French]: 'Ésaïe',
      [Language.German]: 'Jesaja',
      [Language.Italian]: 'Isaia',
      [Language.Hindi]: 'यशायाह',
    },
    abbreviation: CanonBook.Isaiah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.LatterProphets | Category.Prophetic | Category.MajorProphets,
    chapters: 66,
    canon: Canon.Canon,
  },
  [CanonBook.Jeremiah]: {
    name: {
      [Language.English]: 'Jeremiah',
      [Language.Spanish]: 'Jeremías',
      [Language.Chinese]: '耶 利 米 書',
      [Language.Korean]: '예레미야',
      [Language.Japanese]: 'エレミヤ書',
      [Language.Portuguese]: 'Jeremias',
      [Language.French]: 'Jérémie',
      [Language.German]: 'Jeremia',
      [Language.Italian]: 'Geremia',
      [Language.Hindi]: 'यिर्मयाह',
    },
    abbreviation: CanonBook.Jeremiah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.LatterProphets | Category.Prophetic | Category.MajorProphets,
    chapters: 52,
    canon: Canon.Canon,
  },
  [CanonBook.Lamentations]: {
    name: {
      [Language.English]: 'Lamentations',
      [Language.Spanish]: 'Lamentaciones',
      [Language.Chinese]: '耶 利 米 哀 歌',
      [Language.Korean]: '예레미야애가',
      [Language.Japanese]: '哀歌',
      [Language.Portuguese]: 'Lamentações',
      [Language.French]: 'Lamentations',
      [Language.German]: 'Klagelieder',
      [Language.Italian]: 'Lamentazioni',
      [Language.Hindi]: 'विलापगीत',
    },
    abbreviation: CanonBook.Lamentations,
    testament: Testament.Old,
    categories: Category.Writings | Category.Scrolls | Category.Prophetic | Category.MajorProphets,
    chapters: 5,
    canon: Canon.Canon,
  },
  [CanonBook.Ezekiel]: {
    name: {
      [Language.English]: 'Ezekiel',
      [Language.Spanish]: 'Ezequiel',
      [Language.Chinese]: '以 西 結 書',
      [Language.Korean]: '에스겔',
      [Language.Japanese]: 'エゼキエル書',
      [Language.Portuguese]: 'Ezequiel',
      [Language.French]: 'Ézéchiel',
      [Language.German]: 'Hesekiel',
      [Language.Italian]: 'Ezechiele',
      [Language.Hindi]: 'यहेजकेल',
    },
    abbreviation: CanonBook.Ezekiel,
    testament: Testament.Old,
    categories: Category.Prophets | Category.LatterProphets | Category.Prophetic | Category.MajorProphets,
    chapters: 48,
    canon: Canon.Canon,
  },
  [CanonBook.Daniel]: {
    name: {
      [Language.English]: 'Daniel',
      [Language.Spanish]: 'Daniel',
      [Language.Chinese]: '但 以 理 書',
      [Language.Korean]: '다니엘',
      [Language.Japanese]: 'ダニエル書',
      [Language.Portuguese]: 'Daniel',
      [Language.French]: 'Daniel',
      [Language.German]: 'Daniel',
      [Language.Italian]: 'Daniele',
      [Language.Hindi]: 'दानिय्येल',
    },
    abbreviation: CanonBook.Daniel,
    testament: Testament.Old,
    categories: Category.Writings | Category.Historical | Category.Prophetic | Category.MajorProphets,
    chapters: 12,
    canon: Canon.Canon,
  },
  [CanonBook.Hosea]: {
    name: {
      [Language.English]: 'Hosea',
      [Language.Spanish]: 'Oseas',
      [Language.Chinese]: '何 西 阿 書',
      [Language.Korean]: '호세아',
      [Language.Japanese]: 'ホセア書',
      [Language.Portuguese]: 'Oseias',
      [Language.French]: 'Osée',
      [Language.German]: 'Hosea',
      [Language.Italian]: 'Osea',
      [Language.Hindi]: 'होशे',
    },
    abbreviation: CanonBook.Hosea,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 14,
    canon: Canon.Canon,
  },
  [CanonBook.Joel]: {
    name: {
      [Language.English]: 'Joel',
      [Language.Spanish]: 'Joel',
      [Language.Chinese]: '約 珥 書',
      [Language.Korean]: '요엘',
      [Language.Japanese]: 'ヨエル書',
      [Language.Portuguese]: 'Joel',
      [Language.French]: 'Joël',
      [Language.German]: 'Joel',
      [Language.Italian]: 'Gioele',
      [Language.Hindi]: 'योएल',
    },
    abbreviation: CanonBook.Joel,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.Amos]: {
    name: {
      [Language.English]: 'Amos',
      [Language.Spanish]: 'Amós',
      [Language.Chinese]: '阿 摩 司 書',
      [Language.Korean]: '아모스',
      [Language.Japanese]: 'アモス書',
      [Language.Portuguese]: 'Amós',
      [Language.French]: 'Amos',
      [Language.German]: 'Amos',
      [Language.Italian]: 'Amos',
      [Language.Hindi]: 'आमोस',
    },
    abbreviation: CanonBook.Amos,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 9,
    canon: Canon.Canon,
  },
  [CanonBook.Obadiah]: {
    name: {
      [Language.English]: 'Obadiah',
      [Language.Spanish]: 'Abdías',
      [Language.Chinese]: '俄 巴 底 亞 書',
      [Language.Korean]: '오바댜',
      [Language.Japanese]: 'オバデヤ書',
      [Language.Portuguese]: 'Obadias',
      [Language.French]: 'Abdias',
      [Language.German]: 'Obadja',
      [Language.Italian]: 'Abdia',
      [Language.Hindi]: 'ओबद्याह',
    },
    abbreviation: CanonBook.Obadiah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 1,
    canon: Canon.Canon,
  },
  [CanonBook.Jonah]: {
    name: {
      [Language.English]: 'Jonah',
      [Language.Spanish]: 'Jonás',
      [Language.Chinese]: '約 拿 書',
      [Language.Korean]: '요나',
      [Language.Japanese]: 'ヨナ書',
      [Language.Portuguese]: 'Jonas',
      [Language.French]: 'Jonas',
      [Language.German]: 'Jona',
      [Language.Italian]: 'Giona',
      [Language.Hindi]: 'योना',
    },
    abbreviation: CanonBook.Jonah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 4,
    canon: Canon.Canon,
  },
  [CanonBook.Micah]: {
    name: {
      [Language.English]: 'Micah',
      [Language.Spanish]: 'Miqueas',
      [Language.Chinese]: '彌 迦 書',
      [Language.Korean]: '미가',
      [Language.Japanese]: 'ミカ書',
      [Language.Portuguese]: 'Miqueias',
      [Language.French]: 'Michée',
      [Language.German]: 'Mica',
      [Language.Italian]: 'Michea',
      [Language.Hindi]: 'मीका',
    },
    abbreviation: CanonBook.Micah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 7,
    canon: Canon.Canon,
  },
  [CanonBook.Nahum]: {
    name: {
      [Language.English]: 'Nahum',
      [Language.Spanish]: 'Nahúm',
      [Language.Chinese]: '那 鴻 書',
      [Language.Korean]: '나훔',
      [Language.Japanese]: 'ナホム書',
      [Language.Portuguese]: 'Naum',
      [Language.French]: 'Nahum',
      [Language.German]: 'Nahum',
      [Language.Italian]: 'Nahum',
      [Language.Hindi]: 'नहूम',
    },
    abbreviation: CanonBook.Nahum,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.Habakkuk]: {
    name: {
      [Language.English]: 'Habakkuk',
      [Language.Spanish]: 'Habacuc',
      [Language.Chinese]: '哈 巴 谷 書',
      [Language.Korean]: '하박국',
      [Language.Japanese]: 'ハバクク書',
      [Language.Portuguese]: 'Habacuque',
      [Language.French]: 'Habacuc',
      [Language.German]: 'Habakuk',
      [Language.Italian]: 'Abacuc',
      [Language.Hindi]: 'हबक्कूक',
    },
    abbreviation: CanonBook.Habakkuk,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.Zephaniah]: {
    name: {
      [Language.English]: 'Zephaniah',
      [Language.Spanish]: 'Sofonías',
      [Language.Chinese]: '西 番 雅 書',
      [Language.Korean]: '스바냐',
      [Language.Japanese]: 'ゼパニヤ書',
      [Language.Portuguese]: 'Sofonias',
      [Language.French]: 'Sophonie',
      [Language.German]: 'Zephanja',
      [Language.Italian]: 'Sofonia',
      [Language.Hindi]: 'सपन्याह',
    },
    abbreviation: CanonBook.Zephaniah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.Haggai]: {
    name: {
      [Language.English]: 'Haggai',
      [Language.Spanish]: 'Hageo',
      [Language.Chinese]: '哈 該 書',
      [Language.Korean]: '학개',
      [Language.Japanese]: 'ハガイ書',
      [Language.Portuguese]: 'Ageu',
      [Language.French]: 'Aggée',
      [Language.German]: 'Haggai',
      [Language.Italian]: 'Aggeo',
      [Language.Hindi]: 'हाग्गै',
    },
    abbreviation: CanonBook.Haggai,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 2,
    canon: Canon.Canon,
  },
  [CanonBook.Zechariah]: {
    name: {
      [Language.English]: 'Zechariah',
      [Language.Spanish]: 'Zacarías',
      [Language.Chinese]: '撒 迦 利 亞',
      [Language.Korean]: '스가랴',
      [Language.Japanese]: 'ゼカリヤ書',
      [Language.Portuguese]: 'Zacarias',
      [Language.French]: 'Zacharie',
      [Language.German]: 'Sacharja',
      [Language.Italian]: 'Zaccaria',
      [Language.Hindi]: 'जकर्याह',
    },
    abbreviation: CanonBook.Zechariah,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 14,
    canon: Canon.Canon,
  },
  [CanonBook.Malachi]: {
    name: {
      [Language.English]: 'Malachi',
      [Language.Spanish]: 'Malaquías',
      [Language.Chinese]: '瑪 拉 基 書',
      [Language.Korean]: '말라기',
      [Language.Japanese]: 'マラキ書',
      [Language.Portuguese]: 'Malaquias',
      [Language.French]: 'Malachie',
      [Language.German]: 'Maleachi',
      [Language.Italian]: 'Malachia',
      [Language.Hindi]: 'मलाकी',
    },
    abbreviation: CanonBook.Malachi,
    testament: Testament.Old,
    categories: Category.Prophets | Category.MinorProphets | Category.Prophetic,
    chapters: 4,
    canon: Canon.Canon,
  },
  [CanonBook.Matthew]: {
    name: {
      [Language.English]: 'Matthew',
      [Language.Spanish]: 'Mateo',
      [Language.Chinese]: '馬 太 福 音',
      [Language.Korean]: '마태복음',
      [Language.Japanese]: 'マタイの福音書',
      [Language.Portuguese]: 'Mateus',
      [Language.French]: 'Matthieu',
      [Language.German]: 'Matthaeus',
      [Language.Italian]: 'Matteo',
      [Language.Hindi]: 'मत्ती',
    },
    abbreviation: CanonBook.Matthew,
    testament: Testament.New,
    categories: Category.Gospel,
    chapters: 28,
    canon: Canon.Canon,
  },
  [CanonBook.Mark]: {
    name: {
      [Language.English]: 'Mark',
      [Language.Spanish]: 'Marcos',
      [Language.Chinese]: '馬 可 福 音',
      [Language.Korean]: '마가복음',
      [Language.Japanese]: 'マルコの福音書',
      [Language.Portuguese]: 'Marcos',
      [Language.French]: 'Marc',
      [Language.German]: 'Markus',
      [Language.Italian]: 'Marco',
      [Language.Hindi]: 'मरकुस',
    },
    abbreviation: CanonBook.Mark,
    testament: Testament.New,
    categories: Category.Gospel,
    chapters: 16,
    canon: Canon.Canon,
  },
  [CanonBook.Luke]: {
    name: {
      [Language.English]: 'Luke',
      [Language.Spanish]: 'Lucas',
      [Language.Chinese]: '路 加 福 音',
      [Language.Korean]: '누가복음',
      [Language.Japanese]: 'ルカの福音書',
      [Language.Portuguese]: 'Lucas',
      [Language.French]: 'Luc',
      [Language.German]: 'Lukas',
      [Language.Italian]: 'Luca',
      [Language.Hindi]: 'लूका',
    },
    abbreviation: CanonBook.Luke,
    testament: Testament.New,
    categories: Category.Gospel,
    chapters: 24,
    canon: Canon.Canon,
  },
  [CanonBook.John]: {
    name: {
      [Language.English]: 'John',
      [Language.Spanish]: 'Juan',
      [Language.Chinese]: '約 翰 福 音',
      [Language.Korean]: '요한복음',
      [Language.Japanese]: 'ヨハネの福音書',
      [Language.Portuguese]: 'João',
      [Language.French]: 'Jean',
      [Language.German]: 'Johannes',
      [Language.Italian]: 'Giovanni',
      [Language.Hindi]: 'यूहन्ना',
    },
    abbreviation: CanonBook.John,
    testament: Testament.New,
    categories: Category.Gospel,
    chapters: 21,
    canon: Canon.Canon,
  },
  [CanonBook.Acts]: {
    name: {
      [Language.English]: 'Acts',
      [Language.Spanish]: 'Hechos',
      [Language.Chinese]: '使 徒 行 傳',
      [Language.Korean]: '사도행전',
      [Language.Japanese]: '使徒の働き',
      [Language.Portuguese]: 'Atos',
      [Language.French]: 'Actes',
      [Language.German]: 'Apostelgeschichte',
      [Language.Italian]: 'Atti',
      [Language.Hindi]: 'प्रेरितों के काम',
    },
    abbreviation: CanonBook.Acts,
    testament: Testament.New,
    categories: Category.Acts,
    chapters: 28,
    canon: Canon.Canon,
  },
  [CanonBook.Romans]: {
    name: {
      [Language.English]: 'Romans',
      [Language.Spanish]: 'Romanos',
      [Language.Chinese]: '羅 馬 書',
      [Language.Korean]: '로마서',
      [Language.Japanese]: 'ローマ人への手紙',
      [Language.Portuguese]: 'Romanos',
      [Language.French]: 'Romains',
      [Language.German]: 'Roemer',
      [Language.Italian]: 'Romani',
      [Language.Hindi]: 'रोमियों',
    },
    abbreviation: CanonBook.Romans,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 16,
    canon: Canon.Canon,
  },
  [CanonBook.FirstCorinthians]: {
    name: {
      [Language.English]: '1 Corinthians',
      [Language.Spanish]: '1 Corintios',
      [Language.Chinese]: '歌 林 多 前 書',
      [Language.Korean]: '고린도전서',
      [Language.Japanese]: 'コリント人への手紙Ⅰ',
      [Language.Portuguese]: '1 Coríntios',
      [Language.French]: '1 Corinthiens',
      [Language.German]: '1 Korinther',
      [Language.Italian]: '1 Corinzi',
      [Language.Hindi]: '1 कुरिन्थियों',
    },
    abbreviation: CanonBook.FirstCorinthians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 16,
    canon: Canon.Canon,
  },
  [CanonBook.SecondCorinthians]: {
    name: {
      [Language.English]: '2 Corinthians',
      [Language.Spanish]: '2 Corintios',
      [Language.Chinese]: '歌 林 多 後 書',
      [Language.Korean]: '고린도후서',
      [Language.Japanese]: 'コリント人への手紙Ⅱ',
      [Language.Portuguese]: '2 Coríntios',
      [Language.French]: '2 Corinthiens',
      [Language.German]: '2 Korinther',
      [Language.Italian]: '2 Corinzi',
      [Language.Hindi]: '2 कुरिन्थियों',
    },
    abbreviation: CanonBook.SecondCorinthians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 13,
    canon: Canon.Canon,
  },
  [CanonBook.Galatians]: {
    name: {
      [Language.English]: 'Galatians',
      [Language.Spanish]: 'Gálatas',
      [Language.Chinese]: '加 拉 太 書',
      [Language.Korean]: '갈라디아서',
      [Language.Japanese]: 'ガラテヤ人への手紙',
      [Language.Portuguese]: 'Gálatas',
      [Language.French]: 'Galates',
      [Language.German]: 'Galater',
      [Language.Italian]: 'Galati',
      [Language.Hindi]: 'गलातियों',
    },
    abbreviation: CanonBook.Galatians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 6,
    canon: Canon.Canon,
  },
  [CanonBook.Ephesians]: {
    name: {
      [Language.English]: 'Ephesians',
      [Language.Spanish]: 'Efesios',
      [Language.Chinese]: '以 弗 所 書',
      [Language.Korean]: '에베소서',
      [Language.Japanese]: 'エペソ人への手紙',
      [Language.Portuguese]: 'Efésios',
      [Language.French]: 'Éphésiens',
      [Language.German]: 'Epheser',
      [Language.Italian]: 'Efesini',
      [Language.Hindi]: 'इफिसियों',
    },
    abbreviation: CanonBook.Ephesians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 6,
    canon: Canon.Canon,
  },
  [CanonBook.Philippians]: {
    name: {
      [Language.English]: 'Philippians',
      [Language.Spanish]: 'Filipenses',
      [Language.Chinese]: '腓 立 比 書',
      [Language.Korean]: '빌립보서',
      [Language.Japanese]: 'ピリピ人への手紙',
      [Language.Portuguese]: 'Filipenses',
      [Language.French]: 'Philippiens',
      [Language.German]: 'Philipper',
      [Language.Italian]: 'Filippesi',
      [Language.Hindi]: 'फिलिप्पियों',
    },
    abbreviation: CanonBook.Philippians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 4,
    canon: Canon.Canon,
  },
  [CanonBook.Colossians]: {
    name: {
      [Language.English]: 'Colossians',
      [Language.Spanish]: 'Colosenses',
      [Language.Chinese]: '歌 羅 西 書',
      [Language.Korean]: '골로새서',
      [Language.Japanese]: 'コロサイ人への手紙',
      [Language.Portuguese]: 'Colossenses',
      [Language.French]: 'Colossiens',
      [Language.German]: 'Kolosser',
      [Language.Italian]: 'Colossesi',
      [Language.Hindi]: 'कुलुस्सियों',
    },
    abbreviation: CanonBook.Colossians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 4,
    canon: Canon.Canon,
  },
  [CanonBook.FirstThessalonians]: {
    name: {
      [Language.English]: '1 Thessalonians',
      [Language.Spanish]: '1 Tesalonicenses',
      [Language.Chinese]: '帖 撒 羅 尼 迦 前 書',
      [Language.Korean]: '데살로니가전서',
      [Language.Japanese]: 'テサロニケ人への手紙Ⅰ',
      [Language.Portuguese]: '1 Tessalonicenses',
      [Language.French]: '1 Thessaloniciens',
      [Language.German]: '1 Thessalonicher',
      [Language.Italian]: '1 Tessalonicesi',
      [Language.Hindi]: '1 थिस्सलुनीकियों',
    },
    abbreviation: CanonBook.FirstThessalonians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 5,
    canon: Canon.Canon,
  },
  [CanonBook.SecondThessalonians]: {
    name: {
      [Language.English]: '2 Thessalonians',
      [Language.Spanish]: '2 Tesalonicenses',
      [Language.Chinese]: '帖 撒 羅 尼 迦 後 書',
      [Language.Korean]: '데살로니가후서',
      [Language.Japanese]: 'テサロニケ人への手紙Ⅱ',
      [Language.Portuguese]: '2 Tessalonicenses',
      [Language.French]: '2 Thessaloniciens',
      [Language.German]: '2 Thessalonicher',
      [Language.Italian]: '2 Tessalonicesi',
      [Language.Hindi]: '2 थिस्सलुनीकियों',
    },
    abbreviation: CanonBook.SecondThessalonians,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.FirstTimothy]: {
    name: {
      [Language.English]: '1 Timothy',
      [Language.Spanish]: '1 Timoteo',
      [Language.Chinese]: '提 摩 太 前 書',
      [Language.Korean]: '디모데전서',
      [Language.Japanese]: 'テモテへの手紙Ⅰ',
      [Language.Portuguese]: '1 Timóteo',
      [Language.French]: '1 Timothée',
      [Language.German]: '1 Timotheus',
      [Language.Italian]: '1 Timoteo',
      [Language.Hindi]: '1 तीमुथियुस',
    },
    abbreviation: CanonBook.FirstTimothy,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 6,
    canon: Canon.Canon,
  },
  [CanonBook.SecondTimothy]: {
    name: {
      [Language.English]: '2 Timothy',
      [Language.Spanish]: '2 Timoteo',
      [Language.Chinese]: '提 摩 太 後 書',
      [Language.Korean]: '디모데후서',
      [Language.Japanese]: 'テモテへの手紙Ⅱ',
      [Language.Portuguese]: '2 Timóteo',
      [Language.French]: '2 Timothée',
      [Language.German]: '2 Timotheus',
      [Language.Italian]: '2 Timoteo',
      [Language.Hindi]: '2 तीमुथियुस',
    },
    abbreviation: CanonBook.SecondTimothy,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 4,
    canon: Canon.Canon,
  },
  [CanonBook.Titus]: {
    name: {
      [Language.English]: 'Titus',
      [Language.Spanish]: 'Tito',
      [Language.Chinese]: '提 多 書',
      [Language.Korean]: '디도서',
      [Language.Japanese]: 'テトスへの手紙',
      [Language.Portuguese]: 'Tito',
      [Language.French]: 'Tite',
      [Language.German]: 'Titus',
      [Language.Italian]: 'Tito',
      [Language.Hindi]: 'तीतुस',
    },
    abbreviation: CanonBook.Titus,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.Philemon]: {
    name: {
      [Language.English]: 'Philemon',
      [Language.Spanish]: 'Filemón',
      [Language.Chinese]: '腓 利 門 書',
      [Language.Korean]: '빌레몬서',
      [Language.Japanese]: 'ピレモンへの手紙',
      [Language.Portuguese]: 'Filemom',
      [Language.French]: 'Philémon',
      [Language.German]: 'Philemon',
      [Language.Italian]: 'Filemone',
      [Language.Hindi]: 'फिलेमोन',
    },
    abbreviation: CanonBook.Philemon,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 1,
    canon: Canon.Canon,
  },
  [CanonBook.Hebrews]: {
    name: {
      [Language.English]: 'Hebrews',
      [Language.Spanish]: 'Hebreos',
      [Language.Chinese]: '希 伯 來 書',
      [Language.Korean]: '히브리서',
      [Language.Japanese]: 'へブル人への手紙',
      [Language.Portuguese]: 'Hebreus',
      [Language.French]: 'Hébreux',
      [Language.German]: 'Hebraeer',
      [Language.Italian]: 'Ebrei',
      [Language.Hindi]: 'इब्रानियों',
    },
    abbreviation: CanonBook.Hebrews,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 13,
    canon: Canon.Canon,
  },
  [CanonBook.James]: {
    name: {
      [Language.English]: 'James',
      [Language.Spanish]: 'Santiago',
      [Language.Chinese]: '雅 各 書',
      [Language.Korean]: '야고보서',
      [Language.Japanese]: 'ヤコブの手紙',
      [Language.Portuguese]: 'Tiago',
      [Language.French]: 'Jacques',
      [Language.German]: 'Jakobus',
      [Language.Italian]: 'Giacomo',
      [Language.Hindi]: 'याकूब',
    },
    abbreviation: CanonBook.James,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 5,
    canon: Canon.Canon,
  },
  [CanonBook.FirstPeter]: {
    name: {
      [Language.English]: '1 Peter',
      [Language.Spanish]: '1 Pedro',
      [Language.Chinese]: '彼 得 前 書',
      [Language.Korean]: '베드로전서',
      [Language.Japanese]: 'ペテロの手紙Ⅰ',
      [Language.Portuguese]: '1 Pedro',
      [Language.French]: '1 Pierre',
      [Language.German]: '1 Petrus',
      [Language.Italian]: '1 Pietro',
      [Language.Hindi]: '1 पतरस',
    },
    abbreviation: CanonBook.FirstPeter,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 5,
    canon: Canon.Canon,
  },
  [CanonBook.SecondPeter]: {
    name: {
      [Language.English]: '2 Peter',
      [Language.Spanish]: '2 Pedro',
      [Language.Chinese]: '彼 得 後 書',
      [Language.Korean]: '베드로후서',
      [Language.Japanese]: 'ペテロの手紙Ⅱ',
      [Language.Portuguese]: '2 Pedro',
      [Language.French]: '2 Pierre',
      [Language.German]: '2 Petrus',
      [Language.Italian]: '2 Pietro',
      [Language.Hindi]: '2 पतरस',
    },
    abbreviation: CanonBook.SecondPeter,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 3,
    canon: Canon.Canon,
  },
  [CanonBook.FirstJohn]: {
    name: {
      [Language.English]: '1 John',
      [Language.Spanish]: '1 Juan',
      [Language.Chinese]: '約 翰 一 書',
      [Language.Korean]: '요한일서',
      [Language.Japanese]: 'ヨハネの手紙Ⅰ',
      [Language.Portuguese]: '1 João',
      [Language.French]: '1 Jean',
      [Language.German]: '1 Johannes',
      [Language.Italian]: '1 Giovanni',
      [Language.Hindi]: '1 यूहन्ना',
    },
    abbreviation: CanonBook.FirstJohn,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 5,
    canon: Canon.Canon,
  },
  [CanonBook.SecondJohn]: {
    name: {
      [Language.English]: '2 John',
      [Language.Spanish]: '2 Juan',
      [Language.Chinese]: '約 翰 二 書',
      [Language.Korean]: '요한이서',
      [Language.Japanese]: 'ヨハネの手紙Ⅱ',
      [Language.Portuguese]: '2 João',
      [Language.French]: '2 Jean',
      [Language.German]: '2 Johannes',
      [Language.Italian]: '2 Giovanni',
      [Language.Hindi]: '2 यूहन्ना',
    },
    abbreviation: CanonBook.SecondJohn,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 1,
    canon: Canon.Canon,
  },
  [CanonBook.ThirdJohn]: {
    name: {
      [Language.English]: '3 John',
      [Language.Spanish]: '3 Juan',
      [Language.Chinese]: '約 翰 三 書',
      [Language.Korean]: '요한삼서',
      [Language.Japanese]: 'ヨハネの手紙Ⅲ',
      [Language.Portuguese]: '3 João',
      [Language.French]: '3 Jean',
      [Language.German]: '3 Johannes',
      [Language.Italian]: '3 Giovanni',
      [Language.Hindi]: '3 यूहन्ना',
    },
    abbreviation: CanonBook.ThirdJohn,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 1,
    canon: Canon.Canon,
  },
  [CanonBook.Jude]: {
    name: {
      [Language.English]: 'Jude',
      [Language.Spanish]: 'Judas',
      [Language.Chinese]: '猶 大 書',
      [Language.Korean]: '유다서',
      [Language.Japanese]: 'ユダの手紙',
      [Language.Portuguese]: 'Judas',
      [Language.French]: 'Jude',
      [Language.German]: 'Judas',
      [Language.Italian]: 'Giuda',
      [Language.Hindi]: 'यहूदा',
    },
    abbreviation: CanonBook.Jude,
    testament: Testament.New,
    categories: Category.Epistle,
    chapters: 1,
    canon: Canon.Canon,
  },
  [CanonBook.Revelation]: {
    name: {
      [Language.English]: 'Revelation',
      [Language.Spanish]: 'Apocalipsis',
      [Language.Chinese]: '启 示 录',
      [Language.Korean]: '요한계시록',
      [Language.Japanese]: 'ヨハネの黙示録',
      [Language.Portuguese]: 'Apocalipse',
      [Language.French]: 'Apocalypse',
      [Language.German]: 'Offenbarung',
      [Language.Italian]: 'Apocalisse',
      [Language.Hindi]: 'प्रकाशित वाक्य',
    },
    abbreviation: CanonBook.Revelation,
    testament: Testament.New,
    categories: Category.Apocalyptic,
    chapters: 22,
    canon: Canon.Canon,
  },
};

/**
 * Data for all books of the deuterocanon.
 */
export const DeuterocanonBooks: DeuterocanonData = {
  [DeuterocanonBook.Tobit]: {
    name: {
      [Language.English]: 'Tobit',
      [Language.Spanish]: 'Tobit',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: 'Tobi',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.Tobit,
    testament: Testament.Old,
    categories: Category.Novel,
    chapters: 14,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.Judith]: {
    name: {
      [Language.English]: 'Judith',
      [Language.Spanish]: 'Judit',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: 'Giuditta',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.Judith,
    testament: Testament.Old,
    categories: Category.Novel,
    chapters: 16,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.GreekEsther]: {
    name: {
      [Language.English]: 'Greek Esther',
      [Language.Spanish]: 'Ester Griego',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.GreekEsther,
    testament: Testament.Old,
    categories: Category.Novel,
    chapters: 10,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.Wisdom]: {
    name: {
      [Language.English]: 'Wisdom',
      [Language.Spanish]: 'Sabiduría',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: 'Sapienza',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.Wisdom,
    testament: Testament.Old,
    categories: Category.Sapiental,
    chapters: 19,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.Sirach]: {
    name: {
      [Language.English]: 'Sirach',
      [Language.Spanish]: 'Eclesiástico',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: 'Siracide',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.Sirach,
    testament: Testament.Old,
    categories: Category.Sapiental,
    chapters: 51,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.Baruch]: {
    name: {
      [Language.English]: 'Baruch',
      [Language.Spanish]: 'Baruc',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: 'Baruc',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.Baruch,
    testament: Testament.Old,
    categories: Category.Prophetic | Category.MajorProphets,
    chapters: 5,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.LetterOfJeremiah]: {
    name: {
      [Language.English]: 'Letter of Jeremiah',
      [Language.Spanish]: 'Carta de Jeremías',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.LetterOfJeremiah,
    testament: Testament.Old,
    categories: Category.Prophetic | Category.MajorProphets,
    chapters: 1,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.PrayerOfAzariah]: {
    name: {
      [Language.English]: 'Prayer of Azariah',
      [Language.Spanish]: 'Oración de Azarías',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.PrayerOfAzariah,
    testament: Testament.Old,
    categories: CanonBooks[CanonBook.Daniel].categories,
    chapters: 1,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.Susanna]: {
    name: {
      [Language.English]: 'Susanna',
      [Language.Spanish]: 'Susana',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.Susanna,
    testament: Testament.Old,
    categories: CanonBooks[CanonBook.Daniel].categories,
    chapters: 1,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.BelAndTheDragon]: {
    name: {
      [Language.English]: 'Bel and the Dragon',
      [Language.Spanish]: 'Bel y el Dragón',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.BelAndTheDragon,
    testament: Testament.Old,
    categories: CanonBooks[CanonBook.Daniel].categories,
    chapters: 1,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.FirstMaccabees]: {
    name: {
      [Language.English]: '1 Maccabees',
      [Language.Spanish]: '1 Macabeos',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '1 Maccabei',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.FirstMaccabees,
    testament: Testament.Old,
    categories: Category.HistoricalNarrative,
    chapters: 16,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.SecondMaccabees]: {
    name: {
      [Language.English]: '2 Maccabees',
      [Language.Spanish]: '2 Macabeos',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '2 Maccabei',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.SecondMaccabees,
    testament: Testament.Old,
    categories: Category.HistoricalNarrative,
    chapters: 15,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.FirstEsdras]: {
    name: {
      [Language.English]: '1 Esdras',
      [Language.Spanish]: '',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.FirstEsdras,
    testament: Testament.Old,
    categories: Category.HistoricalNarrative,
    chapters: 9,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.PrayerOfManasseh]: {
    name: {
      [Language.English]: 'Prayer of Manasseh',
      [Language.Spanish]: '',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.PrayerOfManasseh,
    testament: Testament.Old,
    categories: Category.Prophetic,
    chapters: 1,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.PsalmOneFiftyOne]: {
    name: {
      [Language.English]: 'Psalm 151',
      [Language.Spanish]: '',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.PsalmOneFiftyOne,
    testament: Testament.Old,
    categories: CanonBooks[CanonBook.Psalm].categories,
    chapters: 1,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.ThirdMaccabees]: {
    name: {
      [Language.English]: '3 Maccabees',
      [Language.Spanish]: '',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.ThirdMaccabees,
    testament: Testament.Old,
    categories: Category.Novel,
    chapters: 7,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.SecondEsdras]: {
    name: {
      [Language.English]: '2 Esdras',
      [Language.Spanish]: '',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.SecondEsdras,
    testament: Testament.Old,
    categories: Category.Apocalyptic,
    chapters: 16,
    canon: Canon.Deuterocanon,
  },
  [DeuterocanonBook.FourthMaccabees]: {
    name: {
      [Language.English]: '4 Maccabees',
      [Language.Spanish]: '',
      [Language.Chinese]: '',
      [Language.Korean]: '',
      [Language.Japanese]: '',
      [Language.Portuguese]: '',
      [Language.French]: '',
      [Language.German]: '',
      [Language.Italian]: '',
      [Language.Hindi]: '',
    },
    abbreviation: DeuterocanonBook.FourthMaccabees,
    testament: Testament.Old,
    categories: Category.Philosophical,
    chapters: 18,
    canon: Canon.Deuterocanon,
  },
};

/**
 * Canonical ordering of books of the Bible, according to Christian canon.
 */
export const CanonicalOrder: { [testament in Testament]: CanonBook[] } = {
  [Testament.Old]: [
    CanonBook.Genesis,
    CanonBook.Exodus,
    CanonBook.Leviticus,
    CanonBook.Numbers,
    CanonBook.Deuteronomy,
    CanonBook.Joshua,
    CanonBook.Judges,
    CanonBook.Ruth,
    CanonBook.FirstSamuel,
    CanonBook.SecondSamuel,
    CanonBook.FirstKings,
    CanonBook.SecondKings,
    CanonBook.FirstChronicles,
    CanonBook.SecondChronicles,
    CanonBook.Ezra,
    CanonBook.Nehemiah,
    CanonBook.Esther,
    CanonBook.Job,
    CanonBook.Psalm,
    CanonBook.Proverbs,
    CanonBook.Ecclesiastes,
    CanonBook.SongOfSongs,
    CanonBook.Isaiah,
    CanonBook.Jeremiah,
    CanonBook.Lamentations,
    CanonBook.Ezekiel,
    CanonBook.Daniel,
    CanonBook.Hosea,
    CanonBook.Joel,
    CanonBook.Amos,
    CanonBook.Obadiah,
    CanonBook.Jonah,
    CanonBook.Micah,
    CanonBook.Nahum,
    CanonBook.Habakkuk,
    CanonBook.Zephaniah,
    CanonBook.Haggai,
    CanonBook.Zechariah,
    CanonBook.Malachi,
  ],
  [Testament.New]: [
    CanonBook.Matthew,
    CanonBook.Mark,
    CanonBook.Luke,
    CanonBook.John,
    CanonBook.Acts,
    CanonBook.Romans,
    CanonBook.FirstCorinthians,
    CanonBook.SecondCorinthians,
    CanonBook.Galatians,
    CanonBook.Ephesians,
    CanonBook.Philippians,
    CanonBook.Colossians,
    CanonBook.FirstThessalonians,
    CanonBook.SecondThessalonians,
    CanonBook.FirstTimothy,
    CanonBook.SecondTimothy,
    CanonBook.Titus,
    CanonBook.Philemon,
    CanonBook.Hebrews,
    CanonBook.James,
    CanonBook.FirstPeter,
    CanonBook.SecondPeter,
    CanonBook.FirstJohn,
    CanonBook.SecondJohn,
    CanonBook.ThirdJohn,
    CanonBook.Jude,
    CanonBook.Revelation,
  ],
};

/**
 * Canonical ordering of detuerocanon books of the Bible, according to Christian canon.
 */
export const DeuterocanonicalOrder: DeuterocanonBook[] = [
  DeuterocanonBook.Tobit,
  DeuterocanonBook.Judith,
  DeuterocanonBook.GreekEsther,
  DeuterocanonBook.Wisdom,
  DeuterocanonBook.Sirach,
  DeuterocanonBook.Baruch,
  DeuterocanonBook.LetterOfJeremiah,
  DeuterocanonBook.PrayerOfAzariah,
  DeuterocanonBook.Susanna,
  DeuterocanonBook.BelAndTheDragon,
  DeuterocanonBook.FirstMaccabees,
  DeuterocanonBook.SecondMaccabees,
  DeuterocanonBook.FirstEsdras,
  DeuterocanonBook.PrayerOfManasseh,
  DeuterocanonBook.PsalmOneFiftyOne,
  DeuterocanonBook.ThirdMaccabees,
  DeuterocanonBook.SecondEsdras,
  DeuterocanonBook.FourthMaccabees,
];

/**
 * Dictionary used for quick lookup of a book of the canon by name for all languages.
 */
export type CanonNameLookupMap = { [language in Language]: CaseInsensitiveMap<CanonBook> };

/**
 * Dictionary used for quick lookup of a book of the deuterocanon by name for all languages.
 */
export type DeuterocanonNameLookupMap = { [language in Language]: CaseInsensitiveMap<DeuterocanonBook> };

/**
 * Generates a mapping of names in a given language to CanonBook key.
 * @param language Language to generate entries for.
 * @returns Array of name => key pairs.
 */
function generateDefaultNameLookupForCanon(language: Language): [string, CanonBook][] {
  return [
    ...Object.entries(CanonBooks)
      .map(
        ([key, data]) =>
          [
            [key, key],
            [data.name[language], key],
          ] as [string, CanonBook][],
      )
      .flat(),
    // Abbreviations do not contain spaces, but we allow them to on lookup.
    ['EX', CanonBook.Exodus],
    ['1 SAM', CanonBook.FirstSamuel],
    ['2 SAM', CanonBook.SecondSamuel],
    ['1 KGS', CanonBook.FirstKings],
    ['2 KGS', CanonBook.SecondKings],
    ['1 CHR', CanonBook.FirstChronicles],
    ['2 CHR', CanonBook.SecondChronicles],
    ['ESTH', CanonBook.Esther],
    ['PSA', CanonBook.Psalm],
    ['ECCL', CanonBook.Ecclesiastes],
    ['EZEK', CanonBook.Ezekiel],
    ['1 COR', CanonBook.FirstCorinthians],
    ['2 COR', CanonBook.SecondCorinthians],
    ['1 THESS', CanonBook.FirstThessalonians],
    ['2 THESS', CanonBook.SecondThessalonians],
    ['1 TIM', CanonBook.FirstTimothy],
    ['2 TIM', CanonBook.SecondTimothy],
    ['1 PET', CanonBook.FirstPeter],
    ['2 PET', CanonBook.SecondPeter],
    ['1 JOHN', CanonBook.FirstJohn],
    ['2 JOHN', CanonBook.SecondJohn],
    ['3 JOHN', CanonBook.ThirdJohn],
  ];
}

function generateExtraNamesForChineseLanguage(): [string, CanonBook][] {
  return Object.values(CanonBooks).map(({ name, abbreviation }) => [
    name[Language.Chinese].replace(/ /g, ''),
    abbreviation,
  ]);
}

/**
 *  Generates a mapping of names in a given language to DeuterocanonBook key.
 * @param language Language to generate entries for.
 * @returns Array of name => key pairs.
 */
function generateDefaultNameLookupForDeuterocanon(language: Language): [string, DeuterocanonBook][] {
  return [
    ...Object.entries(DeuterocanonBooks)
      .map(
        ([key, data]) =>
          [
            [key, key],
            [data.name[language], key],
          ] as [string, DeuterocanonBook][],
      )
      .flat(),
    // Abbreviations do not contain spaces, but we allow them to on lookup.
    ['GK ESTH', DeuterocanonBook.GreekEsther],
    ['EP JER', DeuterocanonBook.LetterOfJeremiah],
    ['PR AZAR', DeuterocanonBook.PrayerOfAzariah],
    ['1 MACC', DeuterocanonBook.FirstMaccabees],
    ['2 MACC', DeuterocanonBook.SecondMaccabees],
    ['1 ESD', DeuterocanonBook.FirstEsdras],
    ['PR MAN', DeuterocanonBook.PrayerOfManasseh],
    ['PS 151', DeuterocanonBook.PsalmOneFiftyOne],
    ['PSA151', DeuterocanonBook.PsalmOneFiftyOne],
    ['PSA 151', DeuterocanonBook.PsalmOneFiftyOne],
    ['3 MACC', DeuterocanonBook.ThirdMaccabees],
    ['2 ESD', DeuterocanonBook.SecondEsdras],
    ['4 MACC', DeuterocanonBook.FourthMaccabees],
  ];
}

/**
 * Map for quick lookup of a book of the canon by name and language.
 */
export const CanonNameLookup: CanonNameLookupMap = {
  [Language.English]: new CaseInsensitiveMap([
    ...generateDefaultNameLookupForCanon(Language.English),
    ['Song of Solomon', CanonBook.SongOfSongs],
    ['Psalms', CanonBook.Psalm],
    ['Acts of the Apostles', CanonBook.Acts],
    ['Phillippians', CanonBook.Philippians],
  ]),
  [Language.Spanish]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.Spanish)),
  [Language.Chinese]: new CaseInsensitiveMap([
    ...generateDefaultNameLookupForCanon(Language.Chinese),
    ...generateExtraNamesForChineseLanguage(),
  ]),
  [Language.Korean]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.Korean)),
  [Language.Japanese]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.Japanese)),
  [Language.Portuguese]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.Portuguese)),
  [Language.French]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.French)),
  [Language.German]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.German)),
  [Language.Italian]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.Italian)),
  [Language.Hindi]: new CaseInsensitiveMap(generateDefaultNameLookupForCanon(Language.Hindi)),
};

/**
 * Map for quick lookup of a book of the deuterocanon by name and language.
 */
export const DeuterocanonNameLookup: DeuterocanonNameLookupMap = {
  [Language.English]: new CaseInsensitiveMap([
    ...generateDefaultNameLookupForDeuterocanon(Language.English),
    ['PSALM151', DeuterocanonBook.PsalmOneFiftyOne],
  ]),
  [Language.Spanish]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Spanish)),
  [Language.Chinese]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Chinese)),
  [Language.Korean]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Korean)),
  [Language.Japanese]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Japanese)),
  [Language.Portuguese]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Portuguese)),
  [Language.French]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.French)),
  [Language.German]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.German)),
  [Language.Italian]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Italian)),
  [Language.Hindi]: new CaseInsensitiveMap(generateDefaultNameLookupForDeuterocanon(Language.Hindi)),
};

/**
 * Finds data about a book of the Bible based on its name or abbreviation.
 * @param name Name of the book.
 * @param language Language.
 * @param includeDeuterocanon Whether to search for detuerocanon books.
 * @returns `BookData` for the bookif it exists. `null` if not found.
 */
export function findBook(name: string, language: Language, includeDeuterocanon: boolean = false): BookData | null {
  const book = CanonNameLookup[language]?.get(name);
  if (!book) {
    if (includeDeuterocanon) {
      const deuteroBook = DeuterocanonNameLookup[language]?.get(name);
      if (deuteroBook) {
        return DeuterocanonBooks[deuteroBook];
      }
    }
    return null;
  }
  return CanonBooks[book];
}
